ago-control-vaadin-site/target/ago-control-vaadin-site.jar opt/agocontrol/site
ago-control-vaadin-site/target/lib/*.jar opt/agocontrol/site/lib
ago-control-vaadin-site/conf/log4j.xml opt/agocontrol/site
ago-control-vaadin-site/conf/ago-control-vaadin-site-ext.properties opt/agocontrol/site
ago-control-vaadin-site/database/*.sql opt/agocontrol/site/database
ago-control-vaadin-site/bin/agosite.service lib/systemd/system
ago-control-vaadin-site/bin/agosite_schema_update.sh opt/agocontrol/site

